### ISSUE TITLE
DevOps

### ISSUE THREAD

**Issue by kerrambit** [kerrambit/RSSFeedify#20]
**DevOps**

The project should start using DevOps, first of all:

- [x] basic tests (unit)
- [x] pipeline (GitHub Actions) - build, run tests, code quality,
- [x] protect main branch

**Comment by kerrambit** [comment]
Create individual issues for tasks.

**Comment by ukkurthisrinivas** [comment]
can you provide me with more information on tasks

**Comment by kerrambit** [comment]
This issue is done. There is built infrastructure for tests, and CI. Now it is time to add unit tests, think about deciding different pipelines etc. but separated issues will be made for these tasks.
